#! python

## Python implementation of MBMA (Van den Bosch & Daelemans 1999)

## Copyright (C) 2011 Folgert Karsdorp
## Author: Folgert Karsdorp <fbkarsdorp@gmail.com>
## URL: <http://github.com/fbkarsdorp/mbmp>
## For licence information, see LICENCE.TXT


from mbmp.train.mbmptrain import main

if __name__ == '__main__':
    main()
